# Meta
title:	projectpage heimedv
description: ""
github_username: 	heimedv


# Server
source:	.
destination: _site
url:	http://primacloud.com
baseurl: ""

# Settings
markdown:	kramdown
permalink:	pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile','CNAME']

